import { Car, Lead, Message, Score, Showroom } from '../types';

export const MOCK_SHOWROOMS: Showroom[] = [
  {
    id: 'HYD-DEL-001',
    name: 'Hyundai Connaught Place',
    city: 'New Delhi',
    address: 'N-1, Connaught Circus, Connaught Place, New Delhi - 110001',
    sales_executive: 'Rajesh Kumar',
    phone: '+91-11-4567-8900',
    active: true
  },
  {
    id: 'HYD-MUM-002',
    name: 'Hyundai Bandra West',
    city: 'Mumbai',
    address: 'Linking Road, Bandra West, Mumbai - 400050',
    sales_executive: 'Priya Sharma',
    phone: '+91-22-9876-5432',
    active: true
  },
  {
    id: 'HYD-BLR-003',
    name: 'Hyundai Indiranagar',
    city: 'Bengaluru',
    address: '100 Feet Road, Indiranagar, Bengaluru - 560038',
    sales_executive: 'Amit Singh',
    phone: '+91-80-1234-5678',
    active: true
  }
];

export const MOCK_SHOWROOM: Showroom = MOCK_SHOWROOMS[0];

export const MOCK_CARS: Car[] = [
  { id: 1, model_name: 'Creta', variant: 'SX(O)', body_type: 'SUV', fuel_type: 'Petrol', transmission: 'Automatic', price_min: 14.0, price_max: 18.0, mileage: '16.8 kmpl', engine_cc: 1497, seating_capacity: 5, colors: ['Atlas White', 'Phantom Black'], features: ['Panoramic Sunroof', 'ADAS Safety Suite', 'Bose Sound System'], image_url: 'https://picsum.photos/seed/Creta/600/400', is_available: true },
  { id: 2, model_name: 'Tucson', variant: 'Platinum', body_type: 'SUV', fuel_type: 'Diesel', transmission: 'Automatic', price_min: 29.0, price_max: 35.5, mileage: '18.0 kmpl', engine_cc: 1997, seating_capacity: 5, colors: ['Atlas White', 'Typhoon Silver'], features: ['AWD', 'ADAS Level 2', '360° Camera'], image_url: 'https://picsum.photos/seed/Tucson/600/400', is_available: true },
  { id: 3, model_name: 'Ioniq 5', variant: 'RWD Long Range', body_type: 'SUV', fuel_type: 'Electric', transmission: 'Automatic', price_min: 44.9, price_max: 47.0, mileage: '631 km range', engine_cc: 0, seating_capacity: 5, colors: ['Matte Gravity Gold', 'Atlas White'], features: ['V2L Technology', 'Vision Roof', 'Ultra-Fast Charging'], image_url: 'https://picsum.photos/seed/Ioniq5/600/400', is_available: true },
  { id: 4, model_name: 'i20', variant: 'Asta (O)', body_type: 'Hatchback', fuel_type: 'Petrol', transmission: 'Manual', price_min: 9.0, price_max: 11.5, mileage: '20.35 kmpl', engine_cc: 1197, seating_capacity: 5, colors: ['Fiery Red', 'Typhoon Silver'], features: ['Wireless Apple CarPlay', 'Sunroof', 'Bose Sound System'], image_url: 'https://picsum.photos/seed/i20/600/400', is_available: true },
  { id: 5, model_name: 'Verna', variant: 'SX (O) Turbo', body_type: 'Sedan', fuel_type: 'Petrol', transmission: 'CVT', price_min: 14.5, price_max: 17.5, mileage: '20.6 kmpl', engine_cc: 1497, seating_capacity: 5, colors: ['Phantom Black', 'Starry Night'], features: ['ADAS Level 2', 'Ventilated Seats', 'Digital Cluster'], image_url: 'https://picsum.photos/seed/Verna/600/400', is_available: true },
];

export const MOCK_SCORE: Score = {
  id: 1, session_id: 'sess-rohan-01', intent_score: 90, satisfaction_score: 95, engagement_score: 85, overall_score: 90, breakdown: {}, computed_at: new Date().toISOString()
};

export const MOCK_LEADS: Lead[] = [
  {
    id: 1,
    session_id: 'sess-rohan-01',
    showroom_id: 'HYD-DEL-001',
    showroom_name: 'Hyundai Connaught Place',
    name: 'Rohan Verma',
    phone: '+91-98112-34567',
    email: 'rohan.verma@gmail.com',
    vehicle_name: 'Hyundai Creta SX(O)',
    budget_min: 14.0,
    budget_max: 18.0,
    fuel_preference: 'Petrol',
    transmission_preference: 'Automatic',
    body_type_preference: 'SUV',
    family_size: 4,
    use_case: 'Family Commute & Highway Trips',
    interested_car_ids: [1],
    lead_score: 90,
    classification: 'HOT',
    status: 'hot',
    test_drive_status: 'requested',
    purchase_timeline: 'Immediate',
    assigned_executive: 'Rajesh Kumar',
    ai_summary: 'Customer looking for a premium 5-seater family SUV for city commute and weekend highway trips. Extremely interested in ADAS safety suite and panoramic sunroof. Requested a test drive and 5-year EMI calculation.',
    reasons: [
      '+20 pts: Specific model selected (Hyundai Creta)',
      '+20 pts: Purchase timeline <= 30 days (Immediate)',
      '+15 pts: Budget identified (₹14.0L - ₹18.0L)',
      '+15 pts: Test drive requested',
      '+10 pts: Finance / EMI interest expressed',
      '+10 pts: High customer satisfaction rating'
    ],
    negotiation_history: [
      {
        id: 101,
        session_id: 'sess-rohan-01',
        car_id: 1,
        round_number: 1,
        customer_offer: 15.5,
        ai_counter: 16.1,
        discount_offered: 0.40,
        status: 'countered',
        notes: 'AI counter-offered standard maximum automated discount of ₹40,000 + free accessory kit. Customer cash discount request of ₹50,000 flagged for human executive approval.',
        timestamp: new Date(Date.now() - 3600000 * 2).toISOString()
      }
    ],
    escalation_reason: 'Customer cash discount request of ₹50,000 exceeds automated limit (max ₹40,000). Senior Executive approval required.',
    notes: 'Followed up via call. Customer requested showroom appointment tomorrow at 3:00 PM for test drive.',
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    score: MOCK_SCORE
  },
  {
    id: 2,
    session_id: 'sess-priya-02',
    showroom_id: 'HYD-MUM-002',
    showroom_name: 'Hyundai Bandra West',
    name: 'Priya Nair',
    phone: '+91-98201-98765',
    email: 'priya.nair@corporate.com',
    vehicle_name: 'Hyundai Tucson Platinum',
    budget_min: 29.0,
    budget_max: 35.0,
    fuel_preference: 'Diesel',
    transmission_preference: 'Automatic',
    body_type_preference: 'SUV',
    family_size: 5,
    use_case: 'Executive Travel & Long Distance',
    interested_car_ids: [2],
    lead_score: 85,
    classification: 'HOT',
    status: 'hot',
    test_drive_status: 'scheduled',
    purchase_timeline: 'Immediate',
    assigned_executive: 'Priya Sharma',
    ai_summary: 'Corporate executive upgrading to mid-size luxury SUV. Interested in Tucson AWD and ceramic coating protection package. Test drive scheduled for Saturday.',
    reasons: [
      '+20 pts: Specific model selected (Hyundai Tucson)',
      '+20 pts: Purchase timeline <= 30 days (Immediate)',
      '+15 pts: Budget identified (₹29.0L - ₹35.0L)',
      '+15 pts: Test drive requested & scheduled',
      '+10 pts: High customer satisfaction',
      '+5 pts: Strong purchase intent signals'
    ],
    negotiation_history: [],
    created_at: new Date(Date.now() - 3600000 * 8).toISOString()
  },
  {
    id: 3,
    session_id: 'sess-anand-03',
    showroom_id: 'HYD-BLR-003',
    showroom_name: 'Hyundai Indiranagar',
    name: 'Anand Kulkarni',
    phone: '+91-99001-11223',
    email: 'anand.k@techpark.io',
    vehicle_name: 'Hyundai Venue Asta',
    budget_min: 10.0,
    budget_max: 13.0,
    fuel_preference: 'Petrol',
    transmission_preference: 'Manual',
    body_type_preference: 'SUV',
    family_size: 4,
    use_case: 'Daily Tech Park Commute',
    interested_car_ids: [1, 4],
    lead_score: 72,
    classification: 'WARM',
    status: 'warm',
    test_drive_status: 'requested',
    purchase_timeline: '1 month',
    assigned_executive: 'Amit Singh',
    ai_summary: 'Tech professional comparing Hyundai Venue vs Maruti Brezza. AI provided factual spec comparison emphasizing Venue interior refinement and 4.4/5 rating.',
    reasons: [
      '+20 pts: Specific model selected (Hyundai Venue)',
      '+20 pts: Purchase timeline within 30 days',
      '+15 pts: Budget identified (₹10.0L - ₹13.0L)',
      '+15 pts: Test drive requested'
    ],
    created_at: new Date(Date.now() - 3600000 * 12).toISOString()
  },
  {
    id: 4,
    session_id: 'sess-kavita-04',
    showroom_id: 'HYD-DEL-001',
    showroom_name: 'Hyundai Connaught Place',
    name: 'Kavita Reddy',
    phone: '+91-98711-22334',
    email: 'kavita.reddy@greenenergy.in',
    vehicle_name: 'Hyundai Ioniq 5 EV',
    budget_min: 44.0,
    budget_max: 48.0,
    fuel_preference: 'Electric',
    transmission_preference: 'Automatic',
    body_type_preference: 'SUV',
    family_size: 4,
    use_case: 'City EV & Green Fleet',
    interested_car_ids: [3],
    lead_score: 80,
    classification: 'HOT',
    status: 'contacted',
    test_drive_status: 'scheduled',
    purchase_timeline: 'Immediate',
    assigned_executive: 'Rajesh Kumar',
    ai_summary: 'EV enthusiast inquiring about Ioniq 5 fast charging and green loan subsidies. High-value luxury EV policy automatically triggered human executive routing.',
    reasons: [
      '+20 pts: Specific model selected (Ioniq 5 EV)',
      '+20 pts: Purchase timeline <= 30 days',
      '+15 pts: Budget identified (₹44.0L - ₹48.0L)',
      '+15 pts: Test drive requested',
      '+10 pts: Finance / Green EMI interest'
    ],
    escalation_reason: 'High-value EV luxury policy requires human manager consultation.',
    created_at: new Date(Date.now() - 3600000 * 18).toISOString()
  },
  {
    id: 5,
    session_id: 'sess-siddharth-05',
    showroom_id: 'HYD-MUM-002',
    showroom_name: 'Hyundai Bandra West',
    name: 'Siddharth Mehta',
    phone: '+91-98210-55443',
    email: 'sid.mehta@finance.com',
    vehicle_name: 'Hyundai Verna Turbo',
    budget_min: 14.5,
    budget_max: 17.5,
    fuel_preference: 'Petrol',
    transmission_preference: 'CVT',
    body_type_preference: 'Sedan',
    family_size: 3,
    use_case: 'Highway Driving & Performance',
    interested_car_ids: [5],
    lead_score: 65,
    classification: 'WARM',
    status: 'new',
    test_drive_status: 'none',
    purchase_timeline: '3 months',
    assigned_executive: 'Priya Sharma',
    ai_summary: 'Sedan buyer comparing Verna Turbo vs Honda City. Inquired about ADAS Level 2 and ventilated seats performance.',
    reasons: [
      '+20 pts: Specific model selected (Hyundai Verna)',
      '+15 pts: Budget identified (₹14.5L - ₹17.5L)',
      '+15 pts: High customer satisfaction',
      '+15 pts: Feature interest (ADAS)'
    ],
    created_at: new Date(Date.now() - 3600000 * 24).toISOString()
  },
  {
    id: 6,
    session_id: 'sess-vikram-06',
    showroom_id: 'HYD-DEL-001',
    showroom_name: 'Hyundai Connaught Place',
    name: 'Vikram Singh',
    phone: '+91-98109-88776',
    email: 'vikram.singh@outlook.com',
    vehicle_name: 'Hyundai Exter',
    budget_min: 6.0,
    budget_max: 9.0,
    fuel_preference: 'Petrol',
    transmission_preference: 'Manual',
    body_type_preference: 'SUV',
    family_size: 5,
    use_case: 'City Commute',
    interested_car_ids: [],
    lead_score: 45,
    classification: 'LOW',
    status: 'new',
    test_drive_status: 'none',
    purchase_timeline: 'Just exploring',
    assigned_executive: 'Rajesh Kumar',
    ai_summary: 'Casual inquiry regarding entry-level micro SUV options under ₹9 Lakhs.',
    reasons: [
      '+15 pts: Budget identified (₹6.0L - ₹9.0L)',
      '+15 pts: High customer satisfaction',
      '+15 pts: Engagement score'
    ],
    created_at: new Date(Date.now() - 3600000 * 30).toISOString()
  },
  {
    id: 7,
    session_id: 'sess-deepak-07',
    showroom_id: 'HYD-BLR-003',
    showroom_name: 'Hyundai Indiranagar',
    name: 'Deepak Joshi',
    phone: '+91-99800-44332',
    email: 'deepak.j@startup.co',
    vehicle_name: 'Hyundai Creta SX',
    budget_min: 15.0,
    budget_max: 16.5,
    fuel_preference: 'Petrol',
    transmission_preference: 'Automatic',
    body_type_preference: 'SUV',
    family_size: 4,
    use_case: 'Family Commute',
    interested_car_ids: [1],
    lead_score: 95,
    classification: 'HOT',
    status: 'converted',
    test_drive_status: 'completed',
    purchase_timeline: 'Immediate',
    assigned_executive: 'Amit Singh',
    ai_summary: 'Customer completed test drive and converted booking on-site with Amit Singh.',
    reasons: [
      '+20 pts: Specific model selected (Creta)',
      '+20 pts: Immediate purchase timeline',
      '+15 pts: Budget identified',
      '+15 pts: Test drive completed',
      '+15 pts: Finance approved',
      '+10 pts: Converted booking'
    ],
    created_at: new Date(Date.now() - 3600000 * 48).toISOString()
  },
  {
    id: 8,
    session_id: 'sess-meera-08',
    showroom_id: 'HYD-MUM-002',
    showroom_name: 'Hyundai Bandra West',
    name: 'Meera Iyer',
    phone: '+91-98200-11223',
    email: 'meera.i@design.com',
    vehicle_name: 'Hyundai Grand i10 Nios',
    budget_min: 4.5,
    budget_max: 5.0,
    fuel_preference: 'Petrol',
    transmission_preference: 'Manual',
    body_type_preference: 'Hatchback',
    family_size: 2,
    use_case: 'City Commute',
    interested_car_ids: [],
    lead_score: 35,
    classification: 'LOW',
    status: 'lost',
    test_drive_status: 'none',
    purchase_timeline: 'Just exploring',
    assigned_executive: 'Priya Sharma',
    ai_summary: 'Customer budget was sub-₹5 Lakhs. AI provided honest trade-off comparison; customer opted for competitor entry model.',
    reasons: [
      '+15 pts: Budget identified (₹4.5L - ₹5.0L)',
      '+10 pts: High customer satisfaction',
      '+10 pts: Basic inquiry'
    ],
    created_at: new Date(Date.now() - 3600000 * 72).toISOString()
  }
];

export const MOCK_MESSAGES: Message[] = [
  { id: 1, session_id: 'sess-rohan-01', role: 'assistant', content: 'Welcome to Hyundai! I am Aria, your AI Sales Executive. May I know your name and what brings you in today?', timestamp: new Date(Date.now() - 3600000 * 4).toISOString() },
  { id: 2, session_id: 'sess-rohan-01', role: 'user', content: 'Hi, I am Rohan Verma. I am looking for a family SUV around 15 to 18 Lakhs in Delhi.', timestamp: new Date(Date.now() - 3600000 * 3.8).toISOString() },
  { id: 3, session_id: 'sess-rohan-01', role: 'assistant', content: 'Great to meet you, Rohan! For a budget around ₹14–18 Lakhs, I strongly recommend the Hyundai Creta SX(O) Petrol Automatic (Rating: 4.6/5, On-Road Delhi: ₹16.5 Lakhs). It features a panoramic sunroof, ADAS safety suite, and premium Bose audio. How many people usually travel with you?', timestamp: new Date(Date.now() - 3600000 * 3.6).toISOString() },
  { id: 4, session_id: 'sess-rohan-01', role: 'user', content: 'We are a family of 4. Can I get a cash discount of 50k on the final price, and can we schedule a test drive?', timestamp: new Date(Date.now() - 3600000 * 3.4).toISOString() },
  { id: 5, session_id: 'sess-rohan-01', role: 'assistant', content: 'I evaluated your offer using our automated pricing policy: our maximum automated discount is ₹40,000 + complimentary All-Weather Accessory Kit. Your request for ₹50,000 cash discount requires approval from our Senior Sales Executive. I have scheduled your test drive request and flagged this for Rajesh Kumar at Connaught Place!', timestamp: new Date(Date.now() - 3600000 * 3.2).toISOString() }
];